version: '3.7'
services:
  aktin-client:
    image: harbor.miracum.org/codex-ap2/aktin-client:1.1.3
    environment:
      BROKER_REQUEST_MEDIATYPE: ${CODEX_FEASIBILITY_AKTIN_CLIENT_BROKER_REQUEST_MEDIATYPE:-application/sq+json}
      BROKER_RESULT_MEDIATYPE: ${CODEX_FEASIBILITY_AKTIN_CLIENT_BROKER_RESULT_MEDIATYPE:-application/json}
      BROKER_ENDPOINT_URI: ${CODEX_FEASIBILITY_AKTIN_CLIENT_BROKER_ENDPOINT_URI:-http://aktin-broker:8080/broker/}
      CLIENT_AUTH_CLASS: ${CODEX_FEASIBILITY_AKTIN_CLIENT_AUTH_CLASS:-org.aktin.broker.client2.auth.ApiKeyAuthentication}
      CLIENT_AUTH_PARAM: ${CODEX_FEASIBILITY_AKTIN_CLIENT_AUTH_PARAM:-xxxApiKey123}
      CLIENT_WEBSOCKET_RECONNECT_SECONDS: ${CODEX_FEASIBILITY_AKTIN_CLIENT_WEBSOCKET_RECONNECT_SECONDS:-10}
      CLIENT_WEBSOCKET_RECONNECT_POLLING: ${CODEX_FEASIBILITY_AKTIN_CLIENT_WEBSOCKET_RECONNECT_POLLING:-true}
      PROCESS_TIMEOUT_SECONDS: ${CODEX_FEASIBILITY_AKTIN_CLIENT_PROCESS_TIMEOUT_SECONDS:-60}
      PROCESS_COMMAND: ${CODEX_FEASIBILITY_AKTIN_CLIENT_PROCESS_COMMAND:-/opt/codex-aktin/call-flare.sh}
      PROCESS_ARGS: ${CODEX_FEASIBILITY_AKTIN_CLIENT_PROCESS_ARGS:-10}
      FLARE_BASE_URL: ${CODEX_FEASIBILITY_AKTIN_CLIENT_FLARE_BASE_URL:-http://node-flare:5000}
      CLIENT_OBFUSCATE: ${CODEX_FEASIBILITY_AKTIN_CLIENT_OBFUSCATE:-true}
    volumes:
      - ./client-exec-scripts/echo.sh:/opt/codex-aktin/echo.sh
      - ./client-exec-scripts/call-cql.sh:/opt/codex-aktin/call-cql.sh
      - ./client-exec-scripts/execute-cql.sh:/opt/codex-aktin/execute-cql.sh
      - ./client-exec-scripts/call-flare.sh:/opt/codex-aktin/call-flare.sh
