#!/bin/bash

# Define default image versions
  # NUM-NODE
    ## AKTIN-Client
    _NUM_NODE_AKTIN_CLIENT_VERSION="1.3.4"

    ## DSF-Client
      ### FHIR
      _NUM_NODE_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION="0.1.0-rc5"
      _NUM_NODE_FHIR_HIGHMED_FHIR_PROXY_VERSION="0.4.0"
      _NUM_NODE_FHIR_POSTGRES_VERSION="13"

      ### BPE
      _NUM_NODE_BPE_CODEX_PROCESSES_AP2_BPE_VERSION="0.1.0-rc5"
      _NUM_NODE_BPE_POSTGRES_VERSION="13"

    ## FHIR-Server
      ### Blaze
      _NUM_NODE_BLAZE_CODEX_BLAZE_VERSION="0.1.0"

      ### HAPI
      _NUM_NODE_HAPI_CODEX_HAPI_VERSION="v5.4.1"
      _NUM_NODE_HAPI_POSTGRES_VERSION="12.6-alpine"

    ## FLARE
    _NUM_NODE_FLARE_CODEX_FLARE_VERSION="0.0.7"

    ## Rev-Proxy
    _NUM_NODE_REV_PROXY_NGINX_UNPRIVILEGED_VERSION="1.20-alpine"

  # ZARS
    ## AKTN-Broker
    _ZARS_AKTIN_BROKER_VERSION="1.3.2"

    ## Backend
    _ZARS_BACKEND_CODEX_FEASIBILITY_BACKEND_VERSION="0.0.9"
    _ZARS_BACKEND_POSTGRES_VERSION="13.1-alpine"

    ## DSF-Broker
      ### FHIR
      _ZARS_DSF_BROKER_FHIR_HIGHMED_FHIR_PROXY_VERSION="0.4.0"
      _ZARS_DSF_BROKER_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION="0.1.0-rc5"
      _ZARS_DSF_BROKER_FHIR_POSTGRES_VERSION="13"

      ### BPE
      _ZARS_DSF_BROKER_BPE_CODEX_PROCESSES_AP2_BPE_VERSION="0.1.0-rc5"
      _ZARS_DSF_BROKER_BPE_POSTGRES_VERSION="13"

    ## Flare
    _ZARS_FLARE_CODEX_FLARE_VERSION="0.0.5"

    ## GUI
    _ZARS_GUI_CODEX_FEASIBILITY_GUI_VERSION="0.1.1"

    ## Keycloak
    _ZARS_KEYCLOAK_CODEX_KEYCLOAK_VERSION="0.0.1"


# Set image versions to default if not set
export NUM_NODE_AKTIN_CLIENT_VERSION="${NUM_NODE_AKTIN_CLIENT_VERSION:-$_NUM_NODE_AKTIN_CLIENT_VERSION}"
export NUM_NODE_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION="${NUM_NODE_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION:-$_NUM_NODE_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION}"
export NUM_NODE_FHIR_HIGHMED_FHIR_PROXY_VERSION="${NUM_NODE_FHIR_HIGHMED_FHIR_PROXY_VERSION:-$_NUM_NODE_FHIR_HIGHMED_FHIR_PROXY_VERSION}"
export NUM_NODE_FHIR_POSTGRES_VERSION="${NUM_NODE_FHIR_POSTGRES_VERSION:-$_NUM_NODE_FHIR_POSTGRES_VERSION}"
export NUM_NODE_BPE_CODEX_PROCESSES_AP2_BPE_VERSION="${NUM_NODE_BPE_CODEX_PROCESSES_AP2_BPE_VERSION:-$_NUM_NODE_BPE_CODEX_PROCESSES_AP2_BPE_VERSION}"
export NUM_NODE_BPE_POSTGRES_VERSION="${NUM_NODE_BPE_POSTGRES_VERSION:-$_NUM_NODE_BPE_POSTGRES_VERSION}"
export NUM_NODE_BLAZE_CODEX_BLAZE_VERSION="${NUM_NODE_BLAZE_CODEX_BLAZE_VERSION:-$_NUM_NODE_BLAZE_CODEX_BLAZE_VERSION}"
export NUM_NODE_HAPI_CODEX_HAPI_VERSION="${NUM_NODE_HAPI_CODEX_HAPI_VERSION:-$_NUM_NODE_HAPI_CODEX_HAPI_VERSION}"
export NUM_NODE_HAPI_POSTGRES_VERSION="${NUM_NODE_HAPI_POSTGRES_VERSION:-$_NUM_NODE_HAPI_POSTGRES_VERSION}"
export NUM_NODE_FLARE_CODEX_FLARE_VERSION="${NUM_NODE_FLARE_CODEX_FLARE_VERSION:-$_NUM_NODE_FLARE_CODEX_FLARE_VERSION}"
export NUM_NODE_REV_PROXY_NGINX_UNPRIVILEGED_VERSION="${NUM_NODE_REV_PROXY_NGINX_UNPRIVILEGED_VERSION:-$_NUM_NODE_REV_PROXY_NGINX_UNPRIVILEGED_VERSION}"
export ZARS_AKTIN_BROKER_VERSION="${ZARS_AKTIN_BROKER_VERSION:-$_ZARS_AKTIN_BROKER_VERSION}"
export ZARS_BACKEND_CODEX_FEASIBILITY_BACKEND_VERSION="${ZARS_BACKEND_CODEX_FEASIBILITY_BACKEND_VERSION:-$_ZARS_BACKEND_CODEX_FEASIBILITY_BACKEND_VERSION}"
export ZARS_BACKEND_POSTGRES_VERSION="${ZARS_BACKEND_POSTGRES_VERSION:-$_ZARS_BACKEND_POSTGRES_VERSION}"
export ZARS_DSF_BROKER_FHIR_HIGHMED_FHIR_PROXY_VERSION="${ZARS_DSF_BROKER_FHIR_HIGHMED_FHIR_PROXY_VERSION:-$_ZARS_DSF_BROKER_FHIR_HIGHMED_FHIR_PROXY_VERSION}"
export ZARS_DSF_BROKER_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION="${ZARS_DSF_BROKER_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION:-$_ZARS_DSF_BROKER_FHIR_CODEX_PROCESSES_AP2_FHIR_VERSION}"
export ZARS_DSF_BROKER_FHIR_POSTGRES_VERSION="${ZARS_DSF_BROKER_FHIR_POSTGRES_VERSION:-$_ZARS_DSF_BROKER_FHIR_POSTGRES_VERSION}"
export ZARS_DSF_BROKER_BPE_CODEX_PROCESSES_AP2_BPE_VERSION="${ZARS_DSF_BROKER_BPE_CODEX_PROCESSES_AP2_BPE_VERSION:-$_ZARS_DSF_BROKER_BPE_CODEX_PROCESSES_AP2_BPE_VERSION}"
export ZARS_DSF_BROKER_BPE_POSTGRES_VERSION="${ZARS_DSF_BROKER_BPE_POSTGRES_VERSION:-$_ZARS_DSF_BROKER_BPE_POSTGRES_VERSION}"
export ZARS_FLARE_CODEX_FLARE_VERSION="${ZARS_FLARE_CODEX_FLARE_VERSION:-$_ZARS_FLARE_CODEX_FLARE_VERSION}"
export ZARS_GUI_CODEX_FEASIBILITY_GUI_VERSION="${ZARS_GUI_CODEX_FEASIBILITY_GUI_VERSION:-$_ZARS_GUI_CODEX_FEASIBILITY_GUI_VERSION}"
export ZARS_KEYCLOAK_CODEX_KEYCLOAK_VERSION="${ZARS_KEYCLOAK_CODEX_KEYCLOAK_VERSION:-$_ZARS_KEYCLOAK_CODEX_KEYCLOAK_VERSION}"
