version: "3.7"

services:
  fhir-server:
    container_name: fhir-server
    image: hapiproject/hapi:v5.4.0
    restart: always
    ports:
      - ${PORT_HAPI_FHIR:-127.0.0.1:8081}:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/fhir?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      VALIDATION_REQUESTS_ENABLED: "false"
      HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY: "true"
    depends_on:
      - db

  db:
    container_name: hapidb
    image: postgres:12.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
