services:
  feasibility-gui:
    image: ghcr.io/medizininformatik-initiative/feasibility-gui:2.0.0
    ports:
    - "443:8443"
    restart: unless-stopped
    volumes:
      - ../auth/cert.pem:/etc/nginx/conf.d/cert.pem
      - ../auth/key.pem:/etc/nginx/conf.d/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mime.types:/etc/nginx/conf.d/mime.types
      - ./deploy-config.json:/usr/share/nginx/html/assets/config/config.deploy.json
      - ./language/de.json:/usr/share/nginx/html/assets/i18n/de.json
      - ./language/en.json:/usr/share/nginx/html/assets/i18n/en.json
