version: '3.7'

services:
  # ZARS FHIR -----------------------------------------------------------------
  dsf-zars-fhir-proxy:
    image: ghcr.io/highmed/fhir_proxy:0.4.0
    volumes:
    - type: bind
      source: ./fhir/proxy/ssl
      target: /usr/local/apache2/ssl
    environment:
      HTTPS_SERVER_NAME_PORT: dsf-zars-fhir-proxy:443
      APP_SERVER_IP: dsf-zars-fhir-app
    depends_on:
    - dsf-zars-fhir-app

  dsf-zars-fhir-app:
    image: ghcr.io/num-codex/codex-processes-ap2/fhir:0.1.0-rc5
    restart: on-failure
    volumes:
    - type: bind
      source: ./fhir/app/conf/dsf-zars-fhir-proxy-client_certificate.p12
      target: /opt/fhir/certs/dsf-zars-fhir-proxy-client_certificate.p12
    - type: bind
      source: ./fhir/app/conf/bundle.xml
      target: /opt/fhir/init/bundle.xml
    environment:
      TZ: Europe/Berlin
      DB_URL: "jdbc:postgresql://dsf-zars-fhir-db/fhir"
      DB_LIQUIBASE_USER: "liquibase_user"
      DB_LIQUIBASE_USER_PASSWORD: "2e385c84-9a3c-4820-b251-5903fd1475e8"
      DB_SERVER_USER_PASSWORD: "jzrMLm6sKjkwCemEuwn98cjH2X3dV2LY"
      CORS_ORIGINS: "http://zars-feasibility-gui-backend"
      ORGANIZATION_IDENTIFIER: "Test_ZARS"
      ORGANIZATION_TYPE: "MeDIC"
      WEBSERVICE_BASE_URL: "https://dsf-zars-fhir-proxy/fhir"
      WEBSERVICE_P12_CERTIFICATE: "/opt/fhir/certs/dsf-zars-fhir-proxy-client_certificate.p12"
      WEBSERVICE_P12_CERTIFICATE_PASSWORD: "password"
      FHIR_INIT_BUNDLE: "/opt/fhir/init/bundle.xml"
      USER_THUMBPRINTS: "70ecc86c9a5c945ac57a2a495fa24828bdece23b19f59ba3466617a86f778b71c33273b6b44aee0bc5a38c1ff63a756dca70e440376bac9adcc9f84be20c4e7a,159db26fbecf96002256ff9f7bd3e53368c4d94b36a12c1714aceaa53207d620946c3675a4971f34f39b42284fee993637cc63cc375f5e6fd2cf93e767a9f1ef"
    depends_on:
    - dsf-zars-fhir-db

  dsf-zars-fhir-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/dsf-zars-fhir-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    volumes:
    - type: volume
      source: dsf-zars-fhir-db-data
      target: /var/lib/postgresql/data
    secrets:
    - dsf-zars-fhir-postgres_password

  # ZARS BPE ------------------------------------------------------------------
  dsf-zars-bpe-app:
    image: ghcr.io/num-codex/codex-processes-ap2/bpe:0.1.0-rc5
    restart: on-failure
    volumes:
    - type: bind
      source: ./bpe/app/last_event
      target: /opt/bpe/last_event
    - type: bind
      source: ./bpe/app/conf/dsf-zars-fhir-proxy-client_certificate.p12
      target: /opt/bpe/certs/dsf-zars-fhir-proxy-client_certificate.p12
    environment:
      TZ: "Europe/Berlin"
      DB_URL: "jdbc:postgresql://dsf-zars-bpe-db/bpe"
      DB_LIQUIBASE_USER: "liquibase_user"
      DB_LIQUIBASE_USER_PASSWORD: "c325ce47-2f98-47e4-8fa7-13d8091761d7"
      DB_SERVER_USER_PASSWORD: "8s4cGYqY41mrWqTmwhZ3beVQcz6wc3Yr"
      DB_CAMUNDA_USER_PASSWORD: "dcPa7a9wTCaTxFk7BdjmCuQp8k29e2eL"
      ORGANIZATION_IDENTIFIER: "Test_ZARS"
      WEBSERVICE_BASE_URL: "https://dsf-zars-fhir-proxy/fhir"
      WEBSERVICE_P12_CERTIFICATE: "/opt/bpe/certs/dsf-zars-fhir-proxy-client_certificate.p12"
      WEBSERVICE_P12_CERTIFICATE_PASSWORD: "password"
      WEBSOCKET_URL: "wss://dsf-zars-fhir-proxy/fhir/ws"
      WEBSOCKET_P12_CERTIFICATE: "/opt/bpe/certs/dsf-zars-fhir-proxy-client_certificate.p12"
      WEBSOCKET_P12_CERTIFICATE_PASSWORD: "password"
      PROCESS_STORE_URL: "http://zars-store:8080/fhir"
    depends_on:
    - dsf-zars-bpe-db
    - dsf-zars-fhir-proxy

  dsf-zars-bpe-db:
    image: postgres:13
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/dsf-zars-bpe-postgres_password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    volumes:
    - type: volume
      source: dsf-zars-bpe-db-data
      target: /var/lib/postgresql/data
    secrets:
    - dsf-zars-bpe-postgres_password

secrets:
  dsf-zars-fhir-postgres_password:
    file: ./fhir/db/conf/postgres_password
  dsf-zars-bpe-postgres_password:
    file: ./bpe/db/conf/postgres_password

volumes:
  dsf-zars-fhir-db-data:
    name: "dsf-zars-fhir-db-data"
  dsf-zars-bpe-db-data:
    name: "dsf-zars-bpe-db-data"
